version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=inventory_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  web:
    build: .
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/inventory_db
      - DEBUG=False
    depends_on:
      - db

  nginx:
    image: nginx:1.25-alpine
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: